export const ApiEndpoints = {
    getUsers: '/users',
    signup: '/users/signup',
    login: '/users/login',
    getOTP: '/users/getOTP',
    resetPassword: '/users/resetPassword',
    verifyOTP: '/users/verify-otp',
    verifyEMAIL: '/users/verify-email',
    createRoom: '/rooms/createRoom',
    getRoomUsers: '/rooms/getUsers',
    getmessages: '/messages',
    createToken: '/token/createToken',
    decodedToken: '/token/decodeToken',
    getRecieverDetails: '/rooms/getRecieverDetails',
};